#!/bin/bash

export __atmutil_name="atmutil"
export __atmutil_repos_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

deno test --unstable --import-map=import_map.json --allow-read --allow-env --allow-run "$@"